package biotools.bioapp;

import biotools.bioseq.*;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Arrays;

public class SequenceVisualiser extends JFrame implements ActionListener {
    private JButton browseButton, openButton, visualise, clear;
    private JFileChooser fileChooser;
    private JTextField nameField;
    public JTextArea textArea;
    public JPanel panel;
    private BufferedReader inFile;
    private DNA dna;
    private RNA rna;
    private Protein protein;

    public SequenceVisualiser() {
        this.setSize(600, 535);
        this.setTitle("Sequence Visualiser");
        this.setResizable(false);
        this.createGUI();
        this.setVisible(true);
    }

    /**
     * Adds the elements to the GUI
     */
    private void createGUI() {
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        Container window = getContentPane();
        window.setLayout(new FlowLayout());

        browseButton = new JButton("Browse");
        window.add(browseButton);
        browseButton.addActionListener(this);

        openButton = new JButton("Open");
        window.add(openButton);
        openButton.addActionListener(this);

        visualise = new JButton("Visualise");
        window.add(visualise);
        visualise.addActionListener(this);

        clear = new JButton("Clear");
        window.add(clear);
        clear.addActionListener(this);

        nameField = new JTextField();
        nameField.setPreferredSize(new Dimension(600, 20));
        window.add(nameField);

        textArea = new JTextArea();
        textArea.setFont(new Font("FreeMono", Font.BOLD, 13));
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);
        textArea.setPreferredSize(new Dimension(600, 400));
        window.add(textArea);

        panel = new JPanel();
        panel.setPreferredSize(new Dimension(600, 30));

        window.add(panel);
    }

    /**
     * Reads the file location in the JTextField named nameField after which it sets the sequence in JTextArea textArea.
     */
    public void readFile() {
        try {
            inFile = new BufferedReader(new FileReader(nameField.getText()));
            textArea.setText("");
            String line;
            while ((line = inFile.readLine()) != null) {
                if (!line.contains(">")) {
                    textArea.append(line.toUpperCase());
                }
            }
            inFile.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null,
                    "File Error: " + e.toString());
        }
    }

    /**
     * Function that gets called if the given sequence is a DNA sequence.
     * It makes a DNA object and calls the function visualiser()
     */
    private void isDNA() {
        dna = new DNA(textArea.getText());
        visualiser();
    }

    /**
     * Function that gets called if the given sequence is a RNA sequence.
     * It makes a RNA object and calls the function visualiser()
     */
    private void isRNA() {
        rna = new RNA(textArea.getText());
        visualiser();
    }

    /**
     * Function that gets called if the given sequence is a protein sequence.
     * It makes a Protein object and calls the function visualiser()
     */
    private void isProtein() {
        protein = new Protein(textArea.getText());
        visualiser();
    }


    /**
     * Looks at what type of sequence has been entered and visualises accordingly using the array Sequence.color.
     * Objects are cleared after visualising.
     */
    public void visualiser() {
        Graphics graphics = panel.getGraphics();
        graphics.clearRect(0, 0, 600, 30);
        Color[] colorArray;
        float length;
        if (dna != null) {
            length = (float) dna.getLength();
            dna.setColor();
            colorArray = dna.getColor();
        } else if (rna != null) {
            length = (float) rna.getLength();
            rna.setColor();
            colorArray = rna.getColor();
        } else {
            length = (float) protein.getLength();
            protein.setColor();
            colorArray = protein.getColor();
        }
        int position = 0;
        int width = Math.round(1f / length * 600); //visualisation might not fit the frame because the round up.
        System.out.println(1f / length * 600);
        System.out.println(width);
        for (int i = 0; i < length; i++) {
            graphics.setColor(colorArray[i]);
            graphics.fillRect(position, 0, width, 30);
            position += width;
        }
        dna = null;
        rna = null;
        protein = null;
    }

    /**
     * Functions as a main for the processes that need to be called after a button is clisked
     * @param event an ActionEvent class generated by clicking on one of the buttons
     */
    public void actionPerformed(ActionEvent event) {
        File selectedFile;
        int reply;

        //Visualise button
        if (event.getSource() == visualise) {
            textArea.setText(textArea.getText().toUpperCase());
            if (textArea.getText().matches("^[ATCG]*$")) {
                isDNA();
            } else if (textArea.getText().matches("^[AUCG]*$")) {
                isRNA();
            } else if (textArea.getText().matches("^[ARNDCQGEHILKMFPSTWYV]*$")) {
                isProtein();
            } else {

                try {
                    throw new NoValidSequence();
                } catch (NoValidSequence noValidSequence) {
                    JOptionPane.showMessageDialog(this, noValidSequence.toString(), "Error", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }

        //Browse button
        if (event.getSource() == browseButton) {
            fileChooser = new JFileChooser();
            reply = fileChooser.showOpenDialog(this);
            if (reply == JFileChooser.APPROVE_OPTION) {
                selectedFile = fileChooser.getSelectedFile();
                nameField.setText(selectedFile.getAbsolutePath());
                readFile();
            }
        }

        //Open GUI button
        if (event.getSource() == openButton) {
            readFile();
        }

        //Clear button
        if (event.getSource() == clear) {
            Graphics g = panel.getGraphics();
            g.clearRect(0, 0, 600, 30);
            textArea.setText("");
        }
    }
}

class NoValidSequence extends Exception {
    public NoValidSequence() {
        super("Input isn't a DNA, RNA or poly-peptide sequence");
    }
}
